### ISSUE TITLE
ExtremeReactors requires mod..

### ISSUE THREAD

**Issue by PaziHD** [ZeroNoRyouki/BigReactors#104]
I have latest version of Extreme Reactors and ZeroCore (0.1.0.5) on 1.11.2.
I am using forge 1.11.2 #2228, recommended version.

It asks for another dependancy.. and I don't know why. I tried removing all dependencies in the mcmod.info file but it still does this. No idea why at all.

**Comment by ZeroNoRyouki** [comment]
Which mod is requesting? Could you send me the fml log or post it somewhere?

**Comment by PaziHD** [comment]
Ooh.. fast response.

Extreme Reactors requests it. https://pastebin.com/gmAbwaSr

**Comment by ZeroNoRyouki** [comment]
Sorry, what I was asking for is what mod is ER asking for. Are you sure that that is the correct crash report? ER is not mentioned once in there

**Comment by PaziHD** [comment]
It's very weird. It doesn't list any mods, its a blank list.

**Comment by PaziHD** [comment]
I'm trying out differant versions of forge. #2296 is very buggy, and does the same problem. I'm trying #2298 now, which is the latest. I'm pretty sure this is a problem from using higher versions of forge in development.

**Comment by PaziHD** [comment]
#2298 just crashes instantly, but I don't think that issue is related. I've done some research, and this problem is common with outdated forge versions but I've been using the latest versions of forge.. Very odd.

**Comment by PaziHD** [comment]
Found this:
[18:07:13] [Client thread/TRACE] [FML/]: Located mcmod.info file in file ExtremeReactors-1.11.2-0.4.5.29.jar
[18:07:13] [Client thread/ERROR] [FML/]: The mcmod.info file in ExtremeReactors-1.11.2-0.4.5.29.jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 8 column 2
	at com.google.gson.internal.Streams.parse(Streams.java:56) ~[Streams.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:84) ~[JsonParser.class:?]
	at com.google.gson.JsonParser.parse(JsonParser.java:59) ~[JsonParser.class:?]
	at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:65) [MetadataCollection.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:63) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:49) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:78) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:141) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:414) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:554) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:233) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440) [bes.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352) [bes.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 8 column 2
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:494) ~[JsonReader.class:?]
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:403) ~[JsonReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:666) ~[TypeAdapters$25.class:?]
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:659) ~[TypeAdapters$25.class:?]
	at com.google.gson.internal.bind.TypeAdapters$25.read(TypeAdapters.java:642) ~[TypeAdapters$25.class:?]
	at com.google.gson.internal.Streams.parse(Streams.java:44) ~[Streams.class:?]
	... 19 more
[18:07:13] [Client thread/DEBUG] [FML/]: Identified a mod of type Lnet/minecraftforge/fml/common/Mod; (erogenousbeef.bigreactors.common.BigReactors) - loading
[18:07:13] [Client thread/TRACE] [bigreactors/]: Parsed dependency info : [zerocore@[1.11.2-0.1.0.5,), forge@[13.20.0.2282,)] [forge@[13.20.0.2282,), zerocore@[1.11.2-0.1.0.5,)] []

**Comment by ZeroNoRyouki** [comment]
Could you post the whole log on pastebin please? Thank you

**Comment by PaziHD** [comment]
The crash here (class 'cah' not found) happens with/without optifine and betterfps.
https://pastebin.com/i1nbny7r

**Comment by ZeroNoRyouki** [comment]
Thank you. Where did you get the ER jar from? I've just tested this in a clean instance using the jar strait from Curse Forge and Forge 13.20.0.2298 and I'm not getting errors. No problems with the mcmod.info file nor any extra required dependencies

**Comment by PaziHD** [comment]
hmm.. i got the jar from curseforge. Ill redownload and say if anything else happens.

**Comment by ZeroNoRyouki** [comment]
If you can, try it with only Forge, ER and Zero CORE like I did just now

**Comment by PaziHD** [comment]
Alright.. ill try that and report back.

**Comment by ZeroNoRyouki** [comment]
There are a bunch of missing mods in that pack, but none of them are related to ER or Zero CORE

[18:07:14] [Client thread/TRACE] [FML/]: Verifying mod requirements are satisfied
[18:07:14] [Client thread/ERROR] [FML/]: The mod rftools (RFTools) requires mods [compatlayer] to be available
[18:07:14] [Client thread/ERROR] [FML/]: Mod rftools (RFTools) requires [compatlayer@[0.1.7,)]
[18:07:14] [Client thread/ERROR] [FML/]: The mod rftoolsdim (RFTools Dimensions) requires mods [compatlayer] to be available
[18:07:14] [Client thread/ERROR] [FML/]: Mod rftoolsdim (RFTools Dimensions) requires [compatlayer@[0.1.6,)]
[18:07:14] [Client thread/ERROR] [FML/]: The mod simplevoidworld (SimpleVoidWorld) requires mods [reborncore] to be available
[18:07:14] [Client thread/ERROR] [FML/]: Mod simplevoidworld (SimpleVoidWorld) requires [reborncore]
[18:07:14] [Client thread/ERROR] [FML/]: The mod tconstruct (Tinkers' Construct) requires mods [mantle] to be available
[18:07:14] [Client thread/ERROR] [FML/]: Mod tconstruct (Tinkers' Construct) requires [mantle@[1.11.2-1.2.0.25,)]
[18:07:14] [Client thread/ERROR] [FML/]: The mod telepads (Telepads) requires mods [subcommonlib] to be available
[18:07:14] [Client thread/ERROR] [FML/]: Mod telepads (Telepads) requires [subcommonlib]
[18:07:14] [Client thread/ERROR] [FML/]: The mod voidcraft (VoidCraft) requires mods [tammodized] to be available
[18:07:14] [Client thread/ERROR] [FML/]: Mod voidcraft (VoidCraft) requires [tammodized@[0.8.4,)]
[18:07:14] [Client thread/ERROR] [FML/]: The mod voidislandcontrol (Void Island Control) requires mods [compatlayer] to be available
[18:07:14] [Client thread/ERROR] [FML/]: Mod voidislandcontrol (Void Island Control) requires [compatlayer]

**Comment by PaziHD** [comment]
Yes, because I installed new mods and was going through their dependancies. I've narrowed down the list a lot now, but now I am getting differant error. Constant crashes. Nothing to do with your mod, but thanks for helping me. You can close this issue btw.

**Comment by PaziHD** [comment]
Pinned it. ArmorPlus.. you nasty mod! lol

**Comment by ZeroNoRyouki** [comment]
Good to know :)

Have fun with ER :)

**Comment by PaziHD** [comment]
Thanks!
