### ISSUE TITLE
OpenComputers API delay

### ISSUE THREAD

**Issue by briman0094** [ZeroNoRyouki/BigReactors#152]
I know several people are already aware of this, but @Vexatos brought to light some new information regarding why this is likely happening. Apparently there is a parameter on the `@Callback` annotation indicating whether an API call can occur multiple times per tick, or whether the call will take an entire tick to complete. I'm guessing when ER switched to `@Callback`, it did not utilize this parameter, and the default is (for some reason) "take an entire tick". Specifying this parameter should fix the issue described in MightyPirates/OpenComputers#2632 and [here](https://oc.cil.li/index.php?/topic/918-big-reactors-grid-control/&page=14), meaning programs such as BRGC should work correctly again.

**Comment by briman0094** [comment]
I can probably PR this later, but I'm at work now and can't start on it until tonight at the earliest.

**Comment by briman0094** [comment]
It looks like [this](https://oc.cil.li/index.php?/topic/918-big-reactors-grid-control/&do=findComment&comment=6877) is a good place to start for whoever fixes this. I'm guessing `direct` simply needs to be set to `true` for all `@Callback` registrations in ExtremeReactors.

**Comment by Vexatos** [comment]
The reason is that `direct=false` (the default) executes the callback on the server thread instead of the computer thread, meaning it is thread-safe for most things; this has the side-effect of making the call take the entire tick. On `ManagedPeripheral`, calls were executed on the computer thread by default since you already are expected to be thread-safe anyway when working with ComputerCraft's `IPeripheral`.

**Comment by Vexatos** [comment]
If you decide to stick to `@Callback`, you could also make use of the other annotation parameters like method documentation, or custom call limits.

**Comment by briman0094** [comment]
Actually, I just realized that the repo is not actually active, so I can't PR this. Not sure why that's the case.

**Comment by ZeroNoRyouki** [comment]
@briman0094 don't waste time on it. The whole need to be re-designed

**Comment by briman0094** [comment]
Could we expect a temporary patch until then, or is the lack of thread safety going to cause issues? If it worked fine with ManagedPeripheral, I would assume it would work fine with `direct = true` as well, at least well enough for a temporary patch.

**Comment by ZeroNoRyouki** [comment]
Yes, I will push out a stop-gap patch probably tomorrow

**Comment by briman0094** [comment]
Excellent news! Thanks!

**Comment by ZeroNoRyouki** [comment]
@Vexatos I'm testing this and set direct=true on my Callbacks but I'm still getting called on the server thread

    @Callback(direct = true)
    public Object[] getEnergyStored(Context context, Arguments arguments) throws Exception {
        return new Object[] { this.getEnergyStored() };
    }

"Server thread@14703" prio=5 tid=0x34 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at erogenousbeef.bigreactors.common.multiblock.computer.ReactorComputerOC.getEnergyStored(ReactorComputerOC.java:148)
	  at generated.li.cil.oc.CallWrapper_erogenousbeef_bigreactors_common_multiblock_computer_ReactorComputerOC_getEnergyStored.call(Unknown Source:-1)
	  at li.cil.oc.server.machine.Callbacks$ComponentCallback.apply(Callbacks.scala:123)
	  at li.cil.oc.server.network.Component$class.invoke(Component.scala:112)
	  at li.cil.oc.server.network.Network$ComponentBuilder$$anon$2.invoke(Network.scala:608)
	  at li.cil.oc.server.machine.Machine.invoke(Machine.scala:360)
	  at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
	  at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5$$anonfun$apply$6.apply(ComponentAPI.scala:78)
	  at li.cil.oc.server.machine.luac.NativeLuaArchitecture.invoke(NativeLuaArchitecture.scala:55)
	  at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:78)
	  at li.cil.oc.server.machine.luac.ComponentAPI$$anonfun$initialize$5.apply(ComponentAPI.scala:74)
	  at li.cil.oc.util.ExtendedLuaState$ExtendedLuaState$$anon$1.invoke(ExtendedLuaState.scala:24)
	  at li.cil.repack.com.naef.jnlua.LuaState.lua_pcall(LuaState.java:-1)
	  at li.cil.repack.com.naef.jnlua.LuaState.call(LuaState.java:681)
	  - locked <0x4305> (a li.cil.repack.com.naef.jnlua.LuaState)
	  at li.cil.oc.server.machine.luac.NativeLuaArchitecture.runSynchronized(NativeLuaArchitecture.scala:177)
	  at li.cil.oc.server.machine.Machine.update(Machine.scala:564)
	  at li.cil.oc.common.tileentity.traits.Computer$class.updateComputer(Computer.scala:121)
	  at li.cil.oc.common.tileentity.Case.updateComputer(Case.scala:28)
	  at li.cil.oc.common.tileentity.traits.Computer$class.updateEntity(Computer.scala:104)
	  at li.cil.oc.common.tileentity.Case.updateEntity(Case.scala:69)
	  at li.cil.oc.common.tileentity.traits.Tickable$class.update(Tickable.scala:6)
	  at li.cil.oc.common.tileentity.Case.update(Case.scala:28)
	  at net.minecraft.world.World.updateEntities(World.java:2001)
	  at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:642)
	  at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:840)
	  at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:741)
	  at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
	  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
	  at java.lang.Thread.run(Thread.java:745)

**Comment by ZeroNoRyouki** [comment]
OK, you cache that in the node

**Comment by ZeroNoRyouki** [comment]
The stop-gap fix is on Curse for review. You must break and replace all your computer ports after the update
