### ISSUE TITLE
Crash when vanilla profiler is enabled

### ISSUE THREAD

**Issue by HenryLoenwind** [ZeroNoRyouki/BigReactors#158]
`erogenousbeef.bigreactors.common.multiblock.MultiblockReactor.updateServer()` calls `Profiler.endSection()` more often then `Profiler.startSection()` leading to an immidiate crash when the profiler is switched on.

The bad call seems to be this one:

```
	at erogenousbeef.bigreactors.common.multiblock.MultiblockReactor.updateServer(MultiblockReactor.java:556)
	at it.zerono.mods.zerocore.api.multiblock.MultiblockControllerBase.updateMultiblockEntity(MultiblockControllerBase.java:533)
	at it.zerono.mods.zerocore.internal.common.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:91)
	at it.zerono.mods.zerocore.internal.common.MultiblockRegistry.tickStart(MultiblockRegistry.java:95)
	at it.zerono.mods.zerocore.internal.common.MultiblockEventHandler.onWorldTick(MultiblockEventHandler.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_190_MultiblockEventHandler_onWorldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreWorldTick(FMLCommonHandler.java:286)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ZeroNoRyouki** [comment]
Thank you for the report. Fixed in the next release
